on:
    push:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
                  aws-region: eu-west-2
            - uses: aws-actions/aws-secretsmanager-get-secrets@v2
              with:
                  secret-ids: kais-test-keys
                  parse-json-secrets: true
            - run: printenv

            - run: |
                  test "$KAIS_TEST_KEYS_PRIVATE_KEY_PASSWORD" &&
                  echo Length ${#KAIS_TEST_KEYS_PRIVATE_KEY_PASSWORD}
